<!doctype html>
<html lang="en">
    <head>
    	<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    	<script>$(document).ajaxError(function(event, jqXHR, ajaxSettings, thrownError){alert(thrownError)});</script>
    	<title>Cloud-Based Social Robotics</title>
    </head>

    <body>
    	<div class="container">
    		<div class="row">
    			<div class="col-4">
        			<?php echo $this->fetch('settings.phtml'); ?>
        		</div>
    			<div class="col-6 pl-5">
        			<?php echo $this->fetch('services.phtml'); ?>
        		</div>
        	</div>
        	<div class="row mt-5">
        		<div class="col-4">
        			<h5>Local</h5>
        			<ul>
        				<li><a href="https://bitbucket.org/socialroboticshub/output/src/master/computer_browser/" target="_blank">Computer Browser</a></li>
        				<li><a href="https://bitbucket.org/socialroboticshub/input/src/master/computer_camera/" target="_blank">Computer Camera</a></li>
        				<li><a href="https://bitbucket.org/socialroboticshub/input/src/master/computer_microphone/" target="_blank">Computer Microphone</a></li>
        				<li><a href="https://bitbucket.org/socialroboticshub/output/src/master/computer_speakers/" target="_blank">Computer Speakers</a></li>
        			</ul>
        		</div>
        	</div>
        </div>

        <div class="modal fade" id="popup" tabindex="-1" role="dialog" aria-hidden="true">
          <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body" id="popupContent">
              </div>
            </div>
          </div>
        </div>
    </body>
</html>
